# wait for it to initialize completely, 
# sudo docker-compose -f jupyter-notebook.yml up
version: "3.9"
services:
  gfb:
    image: jupyter/datascience-notebook
    container_name: gfbds
    restart: always
    ports:
      - "8888:8888"
    networks:
      app_net:
        ipv4_address: 172.16.2.11
    volumes:
      - ./:/home/jovyan

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.2.0/24"
